# Generated by Django 5.2.3 on 2025-06-24 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 24, 18, 18, 18, 23430, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 24, 18, 19, 9, 708163, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 24, 18, 19, 14, 408817, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='section',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='theme',
            name='font_family',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary_color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary_color',
            field=models.CharField(max_length=7),
        ),
    ]
