# Generated by Django 5.2.3 on 2025-06-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_content_created_at_team_created_at_theme_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='content_en',
            field=models.TextField(null=True),
        ),
    ]
